os:
  - linux
  - osx
osx_image: xcode7.2b1
sudo: required
dist: trusty

install:
  - ./environment/bin/install --in-ci --prefix="${HOME}/cosy"
  - ./bin/build-server --in-ci --prefix="${HOME}/cosy"
  - ./bin/build-client --in-ci --prefix="${HOME}/cosy"

before_script:
  - rm -rf output && mkdir -p output

script:
  - "${HOME}/cosy/bin/cosy-check" --output=output --test-format=junit
  - "${HOME}/cosy/bin/cosy-server" start --port=8080
  - for file in ./cosy-client-*.sh; do echo "Installing ${file}..."; "${file}" --target ./cosy-client; done
  - ./tests/user.sh default ./cosy-client/bin/cosy --server=http://127.0.0.1:8080/
  - "${HOME}/cosy/bin/cosy-server" stop

after_failure:
  - cat "${HOME}/.cosy/__busted__/nginx/access.log"
  - cat "${HOME}/.cosy/__busted__/nginx/error.log"
  - cat "${HOME}/.cosy/__scenario__/nginx/access.log"
  - cat "${HOME}/.cosy/__scenario__/nginx/error.log"

after_success:
  - luacov-coveralls --excluse "*" --include "cosy" --exclude "test"

notifications:
  recipients:
    - alban@linard.fr
    - leprieur@lipn.univ-paris13.fr
  email:
    on_success: change
    on_failure: change
