os:
  - linux
  - osx
osx_image: xcode7.2b1
sudo: required
dist: trusty
language: C

install:
  - ./bin/build-client --in-ci
  - ./bin/build-server --prefix=$HOME/cosy/server --in-ci

before_script:
  - rm    -rf output
  - mkdir -p  output/server
  - redis-server --save "" &
  - sleep 1

script:
  - ${HOME}/cosy/server/bin/cosy-check  output/server --test-format=junit
  - ${HOME}/cosy/server/bin/cosy-server start --clean
  - ./tests/user.sh ${HOME}/cosy/server/bin/cosy http://127.0.0.1:8080/
  - ${HOME}/cosy/server/bin/cosy-server stop

notifications:
  recipients:
    - alban@linard.fr
    - leprieur@lipn.univ-paris13.fr
  email:
    on_success: change
    on_failure: always
