os:
  - linux
  - osx

language: C

services:
 - redis-server

install:
  - ./bin/install --prefix=$HOME/cosy/server --mode=server --sourcepath=$(pwd) --in-ci
  - ./bin/install --prefix=$HOME/cosy/client --mode=client --sourcepath=$(pwd) --in-ci

before_script:
  - rm    -rf output
  - mkdir -p  output/server

script:
  - ${HOME}/cosy/server/bin/cosy-check  output/server --test-format=junit
  - ${HOME}/cosy/server/bin/cosy-server start --clean
  - ./tests/user.sh ${HOME}/cosy/server/bin/cosy
  - ${HOME}/cosy/server/bin/cosy-server stop

notifications:
  recipients:
    - alban@linard.fr
    - leprieur@lipn.univ-paris13.fr
  email:
    on_success: change
    on_failure: always
