os:
  - linux
  - osx
osx_image: xcode7.2b1
dist: trusty

sudo: false
language: python

services:
  - redis-server

addons:
  apt:
    packages:
      - git
      - make
      - clang
      - gcc
      - diffutils
      - patch
      - curl
      - unzip
      - perl
      - build-essential
      - wget
      - python
      - libc6-dev
      - libssl-dev
      - libev-dev
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - redis-server
      - imagemagick

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl libev pcre python redis imagemagick wget; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew link --force openssl; fi
  - pip install hererocks

before_script:
  - rm    -rf output
  - mkdir -p  output

install:
  - ./bin/build-server --prefix=$HOME/cosy --in-ci

script:
  - ${HOME}/cosy/bin/cosy-check  output --test-format=junit
  - ${HOME}/cosy/bin/cosy-server start --clean
  - ./tests/user.sh ${HOME}/cosy/bin/cosy http://127.0.0.1:8080/
  - ${HOME}/cosy/server/bin/cosy-server stop

after_success:
  - luacov-coveralls --excluse "*" --include "cosy" --exclude "test"

notifications:
  recipients:
    - alban@linard.fr
    - leprieur@lipn.univ-paris13.fr
  email:
    on_success: change
    on_failure: always
