language: erlang
sudo: false

addons:
  apt:
    packages:
    - diffutils
    - gcc
    - git
    - make
    - patch
    - unzip
    - wget
    - libev-dev
    - libgeoip-dev
    - libssl-dev
    - nginx-extras
    - lua-nginx-redis
    - redis-server

cache:
  directories:
  - $HOME/bin
  - $HOME/etc
  - $HOME/local

before_install:
  - > if [ ! -d $HOME/local ]
      then
        bash bin/install $HOME
      fi

install:
before_script:
script:
  - ./bin/make-check

after_success:
after_failure:
after_script:

notifications:
  recipients:
    - alban@linard.fr
    - leprieur@lipn.univ-paris13.fr
  email:
    on_success: change
    on_failure: always
