os:
  - linux
  - osx
osx_image: xcode7.2b1
sudo: required
dist: trusty

install:
  - ./bin/build-server --prefix=$HOME/cosy --in-ci

before_script:
  - rm -rf output && mkdir -p output
  - redis-server & sleep 1

script:
  - ${HOME}/cosy/bin/cosy-check  --output=output --test-format=junit
  - ${HOME}/cosy/bin/cosy-server start --clean
  - ./tests/user.sh ${HOME}/cosy/bin/cosy http://127.0.0.1:8080/
  - ${HOME}/cosy/bin/cosy-server stop

after_failure:
  - cat ${HOME}/.cosy/nginx/access.log
  - cat ${HOME}/.cosy/nginx/error.log

after_success:
  - luacov-coveralls --excluse "*" --include "cosy" --exclude "test"

notifications:
  recipients:
    - alban@linard.fr
    - leprieur@lipn.univ-paris13.fr
  email:
    on_success: change
    on_failure: change
