os:
  - linux
  - osx
osx_image: xcode7.2b1
sudo: required
dist: trusty

install:
  - ./bin/build-server --in-ci --prefix=$HOME/cosy
  - ./bin/build-client --in-ci

before_script:
  - rm -rf output && mkdir -p output
  - redis-server & sleep 1

script:
  - ${HOME}/cosy/bin/cosy-check --output=output --test-format=junit

after_failure:
  - cat ${HOME}/.cosy/__busted__nginx/access.log
  - cat ${HOME}/.cosy/__busted__nginx/error.log
  - cat ${HOME}/.cosy/__scenario__/access.log
  - cat ${HOME}/.cosy/__scenario__/error.log

after_success:
  - luacov-coveralls --excluse "*" --include "cosy" --exclude "test"

notifications:
  recipients:
    - alban@linard.fr
    - leprieur@lipn.univ-paris13.fr
  email:
    on_success: change
    on_failure: change
